trainersblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class TrainerPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    text = TextAreaField("Text", validators=[DataRequired()])
    submit = SubmitField("Submit", validators=[DataRequired()])

trainersblog/posts/views.py
from flask import flash, redirect, url_for, render_template, Blueprint, abort, request
from flask_login import current_user, login_required
from trainersblog import db
from trainersblog.models import TrainerPost, User
from trainersblog.posts.forms import TrainerPostForm

posts = Blueprint('posts', __name__)


@posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    """
    User creation of post
    """
    form = TrainerPostForm()

    if form.validate_on_submit():

        post = TrainerPost(
            title=form.title.data,
            text=form.text.data,
            user_id=current_user.id
        )
        db.session.add(post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template("posts/create.html", form=form)


@posts.route('/<int:post_id>')
@login_required
def post(post_id):
    post = TrainerPost.query.get_or_404(post_id)
    return render_template('posts/post.html',
                           title=post.title, date=post.date, post=post)


@posts.route('/<int:post_id>/update', methods=['GET', 'POST'])
def update(post_id):
    post = TrainerPost.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    form = TrainerPostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('posts.post', post_id=post_id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text

    return render_template('posts/create.html', title='Updating', form=form)


@posts.route('/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(post_id):
    post = TrainerPost.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted')
    return redirect(url_for('core.index'))


@posts.route('/explore')
@login_required
def view_posts():
    page = request.args.get('page', 1, type=int)
    trainer_posts = TrainerPost.query.filter_by().order_by(
        TrainerPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('posts/explore.html', trainer_posts=trainer_posts)


# trainer_posts = TrainerPost.query.filter_by(author=user).order_by(
#         TrainerPost.date.desc()).paginate(page=page, per_page=5)

trainersblog/users/views.py
from flask import render_template, url_for, redirect, Blueprint, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from trainersblog import db
from trainersblog.models import User, TrainerPost
from trainersblog.users.image_handler import add_pfp
from trainersblog.users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Registers a new user and saves user to the Database
    """
    form = UserRegisterForm()

    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            username=form.username.data,
            password=form.password.data
        )

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Logs in user and redirects them upon successful authentication to home page
    """
    form = UserLoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('Currently logged in as -PLACEHOLDER-')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('users/login.html', form=form)


@users.route('/logout')
def logout():
    """
    Logouts user
    Redirect to Home
    """
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UserUpdateForm()
    if form.validate_on_submit():

        if form.picture.data:
            # pfp = profile picture
            username = current_user.username
            pfp = add_pfp(form.picture.data, username)
            current_user.profile_image = pfp

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Successfully Updated!')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for(
        'static', filename='profile_pics/' + current_user.profile_image)
    return render_template('users/account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    """
    User public profile. Lists all posts for specified user
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    trainer_posts = TrainerPost.query.filter_by(author=user).order_by(
        TrainerPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('users/user_posts.html', trainer_posts=trainer_posts, user=user)

trainersblog/templates/posts/create.html
{% extends 'base.html' %}
{%block content%}
    <div>
        <form method="POST">
            {{form.hidden_tag()}}
            {{form.title.label}}<br>{{form.title}}
            <br>
            <br>
            {{form.text.label}}<br>{{form.text}}
            <br>
            {{form.submit()}}
        </form>
    </div>
{%endblock%}

trainersblog/templates/posts/explore.html
{% extends 'base.html' %}
{%block content%}
{% for post in trainer_posts.items %}
    <div>
        <h2>
            <a href="{{url_for('posts.post', post_id=post.id)}}">{{post.title}}</a>
        <h2>
        <h4>
            Written by: <a href="{{url_for('users.user_posts', username=post.author.username)}}">{{post.author.username}}</a>
        </h4>
        <p class='text-muted'>Published on: {{post.date.strftime("%Y-%m-%d")}}</p>
        <p>{{post.text}}</p>
    <div>
{% endfor %}

    <nav aria-label='Page Navigation example'>
        <ul class="pagination justify-content-center">
            {% for page_num in trainer_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if trainer_posts.page == page_num %}
                    <li class='page-item disabled'>
                        <a class="page-link" href="{{url_for('posts.view_posts', page=page_num)}}">{{ page_num }}</a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="{{url_for('posts.view_posts', page=page_num)}}">{{ page_num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>
    </nav>

{%endblock%}

trainersblog/templates/posts/post.html
{% extends 'base.html' %}
{%block content%}
<div class="bg-light p-5 rounded-lg m-3">
    <div>
        <h5>
            {{post.title}}
        </h5>
        <br>
        <p>
            {{post.text}}
        </p>
    </div>
  {% if post.author == current_user %}
    <div>
        <form action="{{url_for('posts.update', post_id=post.id)}}">
            <input type="submit" class="btn btn-warning" value="Update"/>
        </form>
        <br>
        <form action="{{url_for('posts.delete', post_id=post.id)}}">
            <input type="submit" class="btn btn-danger" value="Delete"/>
        </form>
    </div>
  {% endif %}
</div>
{%endblock%}