trainersblog/core/views.py
from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)


@core.route('/')
def index():
    return render_template('/core/index.html')


@core.route('/about')
def about():
    return render_template('/core/about.html')

trainersblog/posts/views.py
from flask import flash, redirect, url_for, render_template, Blueprint, abort, request
from flask_login import current_user, login_required
from trainersblog import db
from trainersblog.models import TrainerPost, User
from trainersblog.posts.forms import TrainerPostForm

posts = Blueprint('posts', __name__)


@posts.route('/create', methods=['GET', 'POST'])
@login_required
def create_post():
    """
    User creation of post
    """
    form = TrainerPostForm()

    if form.validate_on_submit():

        post = TrainerPost(
            title=form.title.data,
            text=form.text.data,
            user_id=current_user.id
        )
        db.session.add(post)
        db.session.commit()
        flash("Blog Post Created")
        return redirect(url_for('core.index'))

    return render_template("posts/create.html", form=form)


@posts.route('/<int:post_id>')
@login_required
def post(post_id):
    post = TrainerPost.query.get_or_404(post_id)
    return render_template('posts/post.html',
                           title=post.title, date=post.date, post=post)


@posts.route('/<int:post_id>/update', methods=['GET', 'POST'])
def update(post_id):
    post = TrainerPost.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    form = TrainerPostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.text = form.text.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('posts.post', post_id=post_id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.text.data = post.text

    return render_template('posts/create.html', title='Updating', form=form)


@posts.route('/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(post_id):
    post = TrainerPost.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted')
    return redirect(url_for('core.index'))


@posts.route('/explore')
@login_required
def view_posts():
    page = request.args.get('page', 1, type=int)
    trainer_posts = TrainerPost.query.filter_by().order_by(
        TrainerPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('posts/explore.html', trainer_posts=trainer_posts)


# trainer_posts = TrainerPost.query.filter_by(author=user).order_by(
#         TrainerPost.date.desc()).paginate(page=page, per_page=5)

trainersblog/users/views.py
from flask import render_template, url_for, redirect, Blueprint, flash, request
from flask_login import login_user, current_user, logout_user, login_required
from trainersblog import db
from trainersblog.models import User, TrainerPost
from trainersblog.users.image_handler import add_pfp
from trainersblog.users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Registers a new user and saves user to the Database
    """
    form = UserRegisterForm()

    if form.validate_on_submit():
        user = User(
            email=form.email.data,
            username=form.username.data,
            password=form.password.data
        )

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering!')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Logs in user and redirects them upon successful authentication to home page
    """
    form = UserLoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('Currently logged in as -PLACEHOLDER-')

            next = request.args.get('next')

            if next == None or not next[0] == '/':
                next = url_for('core.index')

            return redirect(next)

    return render_template('users/login.html', form=form)


@users.route('/logout')
def logout():
    """
    Logouts user
    Redirect to Home
    """
    logout_user()
    return redirect(url_for('core.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():

    form = UserUpdateForm()
    if form.validate_on_submit():

        if form.picture.data:
            # pfp = profile picture
            username = current_user.username
            pfp = add_pfp(form.picture.data, username)
            current_user.profile_image = pfp

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account Successfully Updated!')
        return redirect(url_for('users.account'))

    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for(
        'static', filename='profile_pics/' + current_user.profile_image)
    return render_template('users/account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    """
    User public profile. Lists all posts for specified user
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    trainer_posts = TrainerPost.query.filter_by(author=user).order_by(
        TrainerPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('users/user_posts.html', trainer_posts=trainer_posts, user=user)

trainersblog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TrainMe</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('core.index')}}">TrainMe</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('core.index')}}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('core.about')}}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.account')}}">My profile</a>
                    </li>
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.login')}}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
                    </li>
                {% elif current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{url_for('posts.create_post')}}">Create Post</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{{url_for('posts.view_posts')}}">Explore</a>
                    </li>
                </ul>
                <form class="d-flex" action="{{url_for('users.logout')}}">
                    <button class="btn btn-warning" type="submit">Logout</button>
                </form>
                {% endif %}
            </div>
        </div>
    </nav>
    {%block content%}


    {%endblock%}


</body>

</html>